######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 14 23:13:07 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
include(../test.pri)

# Input
SOURCES += tst_ircsession.cpp
