######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 31 02:03:44 2008
######################################################################

TEMPLATE = subdirs
CONFIG  += ordered
SUBDIRS += 3rdparty src
